// flow-typed signature: ef75050050ce76600c0d258bfc9760df
// flow-typed version: <<STUB>>/tokenize-text_v^1.1.3/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tokenize-text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tokenize-text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tokenize-text/lib/index' {
  declare module.exports: any;
}

declare module 'tokenize-text/lib/tokens' {
  declare module.exports: any;
}

declare module 'tokenize-text/test/filter' {
  declare module.exports: any;
}

declare module 'tokenize-text/test/flow' {
  declare module.exports: any;
}

declare module 'tokenize-text/test/instance' {
  declare module.exports: any;
}

declare module 'tokenize-text/test/merge' {
  declare module.exports: any;
}

declare module 'tokenize-text/test/re' {
  declare module.exports: any;
}

declare module 'tokenize-text/test/sections' {
  declare module.exports: any;
}

declare module 'tokenize-text/test/tokenize' {
  declare module.exports: any;
}

declare module 'tokenize-text/test/tokens' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tokenize-text/lib/index.js' {
  declare module.exports: $Exports<'tokenize-text/lib/index'>;
}
declare module 'tokenize-text/lib/tokens.js' {
  declare module.exports: $Exports<'tokenize-text/lib/tokens'>;
}
declare module 'tokenize-text/test/filter.js' {
  declare module.exports: $Exports<'tokenize-text/test/filter'>;
}
declare module 'tokenize-text/test/flow.js' {
  declare module.exports: $Exports<'tokenize-text/test/flow'>;
}
declare module 'tokenize-text/test/instance.js' {
  declare module.exports: $Exports<'tokenize-text/test/instance'>;
}
declare module 'tokenize-text/test/merge.js' {
  declare module.exports: $Exports<'tokenize-text/test/merge'>;
}
declare module 'tokenize-text/test/re.js' {
  declare module.exports: $Exports<'tokenize-text/test/re'>;
}
declare module 'tokenize-text/test/sections.js' {
  declare module.exports: $Exports<'tokenize-text/test/sections'>;
}
declare module 'tokenize-text/test/tokenize.js' {
  declare module.exports: $Exports<'tokenize-text/test/tokenize'>;
}
declare module 'tokenize-text/test/tokens.js' {
  declare module.exports: $Exports<'tokenize-text/test/tokens'>;
}
