[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0"
tokio = { version = "1.20", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1"
lazy_static = "1.4"
libc = "0.2"

[build-dependencies]
cxx-build = "1.0"

[lib]
crate-type = ["staticlib"]

[profile.release]
panic = "abort"

[profile.dev]
debug = true
panic = "abort"
