/**
 * @fileoverview gRPC-Web generated client stub for identity.unauth
 * @enhanceable
 * @public
 * @generated
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: identity_unauth.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.identity = {};
proto.identity.unauth = require('./identity-unauth-structs.cjs');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.identity.unauth.IdentityClientServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.identity.unauth.IdentityClientServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.identity.unauth.RegistrationStartRequest,
 *   !proto.identity.unauth.RegistrationStartResponse>}
 */
const methodDescriptor_IdentityClientService_RegisterPasswordUserStart = new grpc.web.MethodDescriptor(
  '/identity.unauth.IdentityClientService/RegisterPasswordUserStart',
  grpc.web.MethodType.UNARY,
  proto.identity.unauth.RegistrationStartRequest,
  proto.identity.unauth.RegistrationStartResponse,
  /**
   * @param {!proto.identity.unauth.RegistrationStartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.identity.unauth.RegistrationStartResponse.deserializeBinary
);


/**
 * @param {!proto.identity.unauth.RegistrationStartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.identity.unauth.RegistrationStartResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.identity.unauth.RegistrationStartResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.identity.unauth.IdentityClientServiceClient.prototype.registerPasswordUserStart =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/RegisterPasswordUserStart',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_RegisterPasswordUserStart,
      callback);
};


/**
 * @param {!proto.identity.unauth.RegistrationStartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.identity.unauth.RegistrationStartResponse>}
 *     Promise that resolves to the response
 */
proto.identity.unauth.IdentityClientServicePromiseClient.prototype.registerPasswordUserStart =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/RegisterPasswordUserStart',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_RegisterPasswordUserStart);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.identity.unauth.ReservedRegistrationStartRequest,
 *   !proto.identity.unauth.RegistrationStartResponse>}
 */
const methodDescriptor_IdentityClientService_RegisterReservedPasswordUserStart = new grpc.web.MethodDescriptor(
  '/identity.unauth.IdentityClientService/RegisterReservedPasswordUserStart',
  grpc.web.MethodType.UNARY,
  proto.identity.unauth.ReservedRegistrationStartRequest,
  proto.identity.unauth.RegistrationStartResponse,
  /**
   * @param {!proto.identity.unauth.ReservedRegistrationStartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.identity.unauth.RegistrationStartResponse.deserializeBinary
);


/**
 * @param {!proto.identity.unauth.ReservedRegistrationStartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.identity.unauth.RegistrationStartResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.identity.unauth.RegistrationStartResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.identity.unauth.IdentityClientServiceClient.prototype.registerReservedPasswordUserStart =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/RegisterReservedPasswordUserStart',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_RegisterReservedPasswordUserStart,
      callback);
};


/**
 * @param {!proto.identity.unauth.ReservedRegistrationStartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.identity.unauth.RegistrationStartResponse>}
 *     Promise that resolves to the response
 */
proto.identity.unauth.IdentityClientServicePromiseClient.prototype.registerReservedPasswordUserStart =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/RegisterReservedPasswordUserStart',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_RegisterReservedPasswordUserStart);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.identity.unauth.RegistrationFinishRequest,
 *   !proto.identity.unauth.RegistrationFinishResponse>}
 */
const methodDescriptor_IdentityClientService_RegisterPasswordUserFinish = new grpc.web.MethodDescriptor(
  '/identity.unauth.IdentityClientService/RegisterPasswordUserFinish',
  grpc.web.MethodType.UNARY,
  proto.identity.unauth.RegistrationFinishRequest,
  proto.identity.unauth.RegistrationFinishResponse,
  /**
   * @param {!proto.identity.unauth.RegistrationFinishRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.identity.unauth.RegistrationFinishResponse.deserializeBinary
);


/**
 * @param {!proto.identity.unauth.RegistrationFinishRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.identity.unauth.RegistrationFinishResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.identity.unauth.RegistrationFinishResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.identity.unauth.IdentityClientServiceClient.prototype.registerPasswordUserFinish =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/RegisterPasswordUserFinish',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_RegisterPasswordUserFinish,
      callback);
};


/**
 * @param {!proto.identity.unauth.RegistrationFinishRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.identity.unauth.RegistrationFinishResponse>}
 *     Promise that resolves to the response
 */
proto.identity.unauth.IdentityClientServicePromiseClient.prototype.registerPasswordUserFinish =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/RegisterPasswordUserFinish',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_RegisterPasswordUserFinish);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.identity.unauth.OpaqueLoginStartRequest,
 *   !proto.identity.unauth.OpaqueLoginStartResponse>}
 */
const methodDescriptor_IdentityClientService_LogInPasswordUserStart = new grpc.web.MethodDescriptor(
  '/identity.unauth.IdentityClientService/LogInPasswordUserStart',
  grpc.web.MethodType.UNARY,
  proto.identity.unauth.OpaqueLoginStartRequest,
  proto.identity.unauth.OpaqueLoginStartResponse,
  /**
   * @param {!proto.identity.unauth.OpaqueLoginStartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.identity.unauth.OpaqueLoginStartResponse.deserializeBinary
);


/**
 * @param {!proto.identity.unauth.OpaqueLoginStartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.identity.unauth.OpaqueLoginStartResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.identity.unauth.OpaqueLoginStartResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.identity.unauth.IdentityClientServiceClient.prototype.logInPasswordUserStart =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/LogInPasswordUserStart',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_LogInPasswordUserStart,
      callback);
};


/**
 * @param {!proto.identity.unauth.OpaqueLoginStartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.identity.unauth.OpaqueLoginStartResponse>}
 *     Promise that resolves to the response
 */
proto.identity.unauth.IdentityClientServicePromiseClient.prototype.logInPasswordUserStart =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/LogInPasswordUserStart',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_LogInPasswordUserStart);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.identity.unauth.OpaqueLoginFinishRequest,
 *   !proto.identity.unauth.OpaqueLoginFinishResponse>}
 */
const methodDescriptor_IdentityClientService_LogInPasswordUserFinish = new grpc.web.MethodDescriptor(
  '/identity.unauth.IdentityClientService/LogInPasswordUserFinish',
  grpc.web.MethodType.UNARY,
  proto.identity.unauth.OpaqueLoginFinishRequest,
  proto.identity.unauth.OpaqueLoginFinishResponse,
  /**
   * @param {!proto.identity.unauth.OpaqueLoginFinishRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.identity.unauth.OpaqueLoginFinishResponse.deserializeBinary
);


/**
 * @param {!proto.identity.unauth.OpaqueLoginFinishRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.identity.unauth.OpaqueLoginFinishResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.identity.unauth.OpaqueLoginFinishResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.identity.unauth.IdentityClientServiceClient.prototype.logInPasswordUserFinish =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/LogInPasswordUserFinish',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_LogInPasswordUserFinish,
      callback);
};


/**
 * @param {!proto.identity.unauth.OpaqueLoginFinishRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.identity.unauth.OpaqueLoginFinishResponse>}
 *     Promise that resolves to the response
 */
proto.identity.unauth.IdentityClientServicePromiseClient.prototype.logInPasswordUserFinish =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/LogInPasswordUserFinish',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_LogInPasswordUserFinish);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.identity.unauth.WalletLoginRequest,
 *   !proto.identity.unauth.WalletLoginResponse>}
 */
const methodDescriptor_IdentityClientService_LogInWalletUser = new grpc.web.MethodDescriptor(
  '/identity.unauth.IdentityClientService/LogInWalletUser',
  grpc.web.MethodType.UNARY,
  proto.identity.unauth.WalletLoginRequest,
  proto.identity.unauth.WalletLoginResponse,
  /**
   * @param {!proto.identity.unauth.WalletLoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.identity.unauth.WalletLoginResponse.deserializeBinary
);


/**
 * @param {!proto.identity.unauth.WalletLoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.identity.unauth.WalletLoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.identity.unauth.WalletLoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.identity.unauth.IdentityClientServiceClient.prototype.logInWalletUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/LogInWalletUser',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_LogInWalletUser,
      callback);
};


/**
 * @param {!proto.identity.unauth.WalletLoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.identity.unauth.WalletLoginResponse>}
 *     Promise that resolves to the response
 */
proto.identity.unauth.IdentityClientServicePromiseClient.prototype.logInWalletUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/LogInWalletUser',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_LogInWalletUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.identity.unauth.ReservedWalletLoginRequest,
 *   !proto.identity.unauth.WalletLoginResponse>}
 */
const methodDescriptor_IdentityClientService_LogInReservedWalletUser = new grpc.web.MethodDescriptor(
  '/identity.unauth.IdentityClientService/LogInReservedWalletUser',
  grpc.web.MethodType.UNARY,
  proto.identity.unauth.ReservedWalletLoginRequest,
  proto.identity.unauth.WalletLoginResponse,
  /**
   * @param {!proto.identity.unauth.ReservedWalletLoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.identity.unauth.WalletLoginResponse.deserializeBinary
);


/**
 * @param {!proto.identity.unauth.ReservedWalletLoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.identity.unauth.WalletLoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.identity.unauth.WalletLoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.identity.unauth.IdentityClientServiceClient.prototype.logInReservedWalletUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/LogInReservedWalletUser',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_LogInReservedWalletUser,
      callback);
};


/**
 * @param {!proto.identity.unauth.ReservedWalletLoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.identity.unauth.WalletLoginResponse>}
 *     Promise that resolves to the response
 */
proto.identity.unauth.IdentityClientServicePromiseClient.prototype.logInReservedWalletUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/LogInReservedWalletUser',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_LogInReservedWalletUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.identity.unauth.SecondaryDeviceLoginRequest,
 *   !proto.identity.unauth.SecondaryDeviceLoginResponse>}
 */
const methodDescriptor_IdentityClientService_LogInSecondaryDevice = new grpc.web.MethodDescriptor(
  '/identity.unauth.IdentityClientService/LogInSecondaryDevice',
  grpc.web.MethodType.UNARY,
  proto.identity.unauth.SecondaryDeviceLoginRequest,
  proto.identity.unauth.SecondaryDeviceLoginResponse,
  /**
   * @param {!proto.identity.unauth.SecondaryDeviceLoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.identity.unauth.SecondaryDeviceLoginResponse.deserializeBinary
);


/**
 * @param {!proto.identity.unauth.SecondaryDeviceLoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.identity.unauth.SecondaryDeviceLoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.identity.unauth.SecondaryDeviceLoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.identity.unauth.IdentityClientServiceClient.prototype.logInSecondaryDevice =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/LogInSecondaryDevice',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_LogInSecondaryDevice,
      callback);
};


/**
 * @param {!proto.identity.unauth.SecondaryDeviceLoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.identity.unauth.SecondaryDeviceLoginResponse>}
 *     Promise that resolves to the response
 */
proto.identity.unauth.IdentityClientServicePromiseClient.prototype.logInSecondaryDevice =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/LogInSecondaryDevice',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_LogInSecondaryDevice);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.identity.unauth.Empty,
 *   !proto.identity.unauth.GenerateNonceResponse>}
 */
const methodDescriptor_IdentityClientService_GenerateNonce = new grpc.web.MethodDescriptor(
  '/identity.unauth.IdentityClientService/GenerateNonce',
  grpc.web.MethodType.UNARY,
  proto.identity.unauth.Empty,
  proto.identity.unauth.GenerateNonceResponse,
  /**
   * @param {!proto.identity.unauth.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.identity.unauth.GenerateNonceResponse.deserializeBinary
);


/**
 * @param {!proto.identity.unauth.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.identity.unauth.GenerateNonceResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.identity.unauth.GenerateNonceResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.identity.unauth.IdentityClientServiceClient.prototype.generateNonce =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/GenerateNonce',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_GenerateNonce,
      callback);
};


/**
 * @param {!proto.identity.unauth.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.identity.unauth.GenerateNonceResponse>}
 *     Promise that resolves to the response
 */
proto.identity.unauth.IdentityClientServicePromiseClient.prototype.generateNonce =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/GenerateNonce',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_GenerateNonce);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.identity.unauth.VerifyUserAccessTokenRequest,
 *   !proto.identity.unauth.VerifyUserAccessTokenResponse>}
 */
const methodDescriptor_IdentityClientService_VerifyUserAccessToken = new grpc.web.MethodDescriptor(
  '/identity.unauth.IdentityClientService/VerifyUserAccessToken',
  grpc.web.MethodType.UNARY,
  proto.identity.unauth.VerifyUserAccessTokenRequest,
  proto.identity.unauth.VerifyUserAccessTokenResponse,
  /**
   * @param {!proto.identity.unauth.VerifyUserAccessTokenRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.identity.unauth.VerifyUserAccessTokenResponse.deserializeBinary
);


/**
 * @param {!proto.identity.unauth.VerifyUserAccessTokenRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.identity.unauth.VerifyUserAccessTokenResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.identity.unauth.VerifyUserAccessTokenResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.identity.unauth.IdentityClientServiceClient.prototype.verifyUserAccessToken =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/VerifyUserAccessToken',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_VerifyUserAccessToken,
      callback);
};


/**
 * @param {!proto.identity.unauth.VerifyUserAccessTokenRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.identity.unauth.VerifyUserAccessTokenResponse>}
 *     Promise that resolves to the response
 */
proto.identity.unauth.IdentityClientServicePromiseClient.prototype.verifyUserAccessToken =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/VerifyUserAccessToken',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_VerifyUserAccessToken);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.identity.unauth.AddReservedUsernamesRequest,
 *   !proto.identity.unauth.Empty>}
 */
const methodDescriptor_IdentityClientService_AddReservedUsernames = new grpc.web.MethodDescriptor(
  '/identity.unauth.IdentityClientService/AddReservedUsernames',
  grpc.web.MethodType.UNARY,
  proto.identity.unauth.AddReservedUsernamesRequest,
  proto.identity.unauth.Empty,
  /**
   * @param {!proto.identity.unauth.AddReservedUsernamesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.identity.unauth.Empty.deserializeBinary
);


/**
 * @param {!proto.identity.unauth.AddReservedUsernamesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.identity.unauth.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.identity.unauth.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.identity.unauth.IdentityClientServiceClient.prototype.addReservedUsernames =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/AddReservedUsernames',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_AddReservedUsernames,
      callback);
};


/**
 * @param {!proto.identity.unauth.AddReservedUsernamesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.identity.unauth.Empty>}
 *     Promise that resolves to the response
 */
proto.identity.unauth.IdentityClientServicePromiseClient.prototype.addReservedUsernames =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/AddReservedUsernames',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_AddReservedUsernames);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.identity.unauth.RemoveReservedUsernameRequest,
 *   !proto.identity.unauth.Empty>}
 */
const methodDescriptor_IdentityClientService_RemoveReservedUsername = new grpc.web.MethodDescriptor(
  '/identity.unauth.IdentityClientService/RemoveReservedUsername',
  grpc.web.MethodType.UNARY,
  proto.identity.unauth.RemoveReservedUsernameRequest,
  proto.identity.unauth.Empty,
  /**
   * @param {!proto.identity.unauth.RemoveReservedUsernameRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.identity.unauth.Empty.deserializeBinary
);


/**
 * @param {!proto.identity.unauth.RemoveReservedUsernameRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.identity.unauth.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.identity.unauth.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.identity.unauth.IdentityClientServiceClient.prototype.removeReservedUsername =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/RemoveReservedUsername',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_RemoveReservedUsername,
      callback);
};


/**
 * @param {!proto.identity.unauth.RemoveReservedUsernameRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.identity.unauth.Empty>}
 *     Promise that resolves to the response
 */
proto.identity.unauth.IdentityClientServicePromiseClient.prototype.removeReservedUsername =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/RemoveReservedUsername',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_RemoveReservedUsername);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.identity.unauth.Empty,
 *   !proto.identity.unauth.Empty>}
 */
const methodDescriptor_IdentityClientService_Ping = new grpc.web.MethodDescriptor(
  '/identity.unauth.IdentityClientService/Ping',
  grpc.web.MethodType.UNARY,
  proto.identity.unauth.Empty,
  proto.identity.unauth.Empty,
  /**
   * @param {!proto.identity.unauth.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.identity.unauth.Empty.deserializeBinary
);


/**
 * @param {!proto.identity.unauth.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.identity.unauth.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.identity.unauth.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.identity.unauth.IdentityClientServiceClient.prototype.ping =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/Ping',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_Ping,
      callback);
};


/**
 * @param {!proto.identity.unauth.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.identity.unauth.Empty>}
 *     Promise that resolves to the response
 */
proto.identity.unauth.IdentityClientServicePromiseClient.prototype.ping =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/identity.unauth.IdentityClientService/Ping',
      request,
      metadata || {},
      methodDescriptor_IdentityClientService_Ping);
};


module.exports = proto.identity.unauth;

