// flow-typed signature: 3f4414dfa9d8b9e10e1a2f23aae1dfb0
// flow-typed version: <<STUB>>/@react-native-community/cameraroll_v^1.0.5/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/cameraroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-community/cameraroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-community/cameraroll/jest.setup' {
  declare module.exports: any;
}

declare module '@react-native-community/cameraroll/js/__mocks__/nativeInterface' {
  declare module.exports: any;
}

declare module '@react-native-community/cameraroll/js/__tests__/CameraRollTest' {
  declare module.exports: any;
}

declare module '@react-native-community/cameraroll/js/CameraRoll' {
  declare module.exports: any;
}

declare module '@react-native-community/cameraroll/js/nativeInterface' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-community/cameraroll/jest.setup.js' {
  declare module.exports: $Exports<'@react-native-community/cameraroll/jest.setup'>;
}
declare module '@react-native-community/cameraroll/js/__mocks__/nativeInterface.js' {
  declare module.exports: $Exports<'@react-native-community/cameraroll/js/__mocks__/nativeInterface'>;
}
declare module '@react-native-community/cameraroll/js/__tests__/CameraRollTest.js' {
  declare module.exports: $Exports<'@react-native-community/cameraroll/js/__tests__/CameraRollTest'>;
}
declare module '@react-native-community/cameraroll/js/CameraRoll.js' {
  declare module.exports: $Exports<'@react-native-community/cameraroll/js/CameraRoll'>;
}
declare module '@react-native-community/cameraroll/js/nativeInterface.js' {
  declare module.exports: $Exports<'@react-native-community/cameraroll/js/nativeInterface'>;
}
