// flow-typed signature: d67dec188e760529755a64aff7690a3e
// flow-typed version: <<STUB>>/@react-native-community/netinfo_v^2.0.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/netinfo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-community/netinfo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-community/netinfo/jest.setup' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/js/__tests__/eventListenerCallbacks' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/js/__tests__/eventListenerManagement' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/js/__tests__/getConnectionInfo' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/js/__tests__/isConnected' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/js/__tests__/isConnectionExpensiveAndroid' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/js/__tests__/isConnectionExpensiveIOS' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/js/index' {
  declare module.exports: any;
}

declare module '@react-native-community/netinfo/js/nativeInterface' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-community/netinfo/jest.setup.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/jest.setup'>;
}
declare module '@react-native-community/netinfo/js/__tests__/eventListenerCallbacks.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/js/__tests__/eventListenerCallbacks'>;
}
declare module '@react-native-community/netinfo/js/__tests__/eventListenerManagement.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/js/__tests__/eventListenerManagement'>;
}
declare module '@react-native-community/netinfo/js/__tests__/getConnectionInfo.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/js/__tests__/getConnectionInfo'>;
}
declare module '@react-native-community/netinfo/js/__tests__/isConnected.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/js/__tests__/isConnected'>;
}
declare module '@react-native-community/netinfo/js/__tests__/isConnectionExpensiveAndroid.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/js/__tests__/isConnectionExpensiveAndroid'>;
}
declare module '@react-native-community/netinfo/js/__tests__/isConnectionExpensiveIOS.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/js/__tests__/isConnectionExpensiveIOS'>;
}
declare module '@react-native-community/netinfo/js/index.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/js/index'>;
}
declare module '@react-native-community/netinfo/js/nativeInterface.js' {
  declare module.exports: $Exports<'@react-native-community/netinfo/js/nativeInterface'>;
}
