[package]
name = "blob_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"
tokio = { version = "1.21", features = ["rt-multi-thread"] }
tokio-stream = "0.1"
tonic = "0.8"
prost = "0.11"
lazy_static = "1.4"

[build-dependencies]
cxx-build = "1.0"
tonic-build = "0.8"

[lib]
crate-type=["staticlib"]
