[package]
name = "feature-flags"
description = "Feature Flags service"
homepage = "https://comm.app"
license = "BSD-3-Clause"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
aws-config = "0.51.0"
aws-types = "0.51.0"
aws-sdk-dynamodb = "0.21.0"
clap = { version = "4.0", features = ["derive", "env"] }
http = "0.2"
once_cell = "1.17"
comm-services-lib = { path = "../comm-services-lib" }
tokio = { version = "1.24", features = ["rt-multi-thread", "macros"]}
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"]}
