[package]
name = "feature-flags"
description = "Feature Flags service"
homepage = "https://comm.app"
license = "BSD-3-Clause"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive", "env"] }
once_cell = "1.17"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"]}
