steps:
  - label: ':robot_face: Android Build'
    command:
      - 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
      - 'source /root/.cargo/env'
      - 'rustup target add aarch64-linux-android arm-linux-androideabi i686-linux-android x86_64-linux-android'
      - 'apt update && apt install -y autoconf libtool build-essential cmake git libgtest-dev libssl-dev zlib1g-dev'
      - 'scripts/install_protobuf.sh'
      - 'yarn ci-cleaninstall'
      - 'cd native/android'
      - './gradlew clean && ./gradlew bundleRelease --no-daemon "-Dorg.gradle.jvmargs=-Xmx32g -XX:MaxMetaspaceSize=8g"'
    retry:
      automatic: true
    plugins:
      - docker#v5.3.0:
          image: 'reactnativecommunity/react-native-android:latest'
          shell: ['/bin/bash', '-e', '-c']
          propagate-environment: true
    agents:
      - 'autoscaling=true'
