steps:
  - command:
      - 'yarn cleaninstall --frozen-lockfile --skip-optional'
      - 'cd native/android'
      - './gradlew bundleRelease --no-daemon "-Dorg.gradle.jvmargs=-Xmx32g -XX:MaxPermSize=32g -XX:+HeapDumpOnOutOfMemoryError"'
    plugins:
      - docker#v3.13.0:
          image: 'reactnativecommunity/react-native-android:latest'
          environment:
            - 'BUILDKITE=true'
    agents:
      - 'autoscaling=true'
