steps:
  - label: ':nix: Blob Unittests'
    command:
      - 'cd services/blob'
      - 'nix develop --accept-flake-config --command cargo test'
    retry:
      automatic: true
    plugins:
      - docker#v5.3.0:
          image: 'nixos/nix'
          shell: ['/bin/bash', '-e', '-c']
          propagate-environment: true
    agents:
      - 'autoscaling=true'
