steps:
  - label: ':nix: Blob Unittests'
    command:
      - 'apt update && apt install -y autoconf libtool build-essential cmake git'
      - './scripts/install_protobuf.sh'
      - 'cd services/blob'
      - 'cargo test'
    retry:
      automatic: true
    plugins:
      - docker#v5.3.0:
          image: 'rust:1.74.0'
          propagate-environment: true
    agents:
      - 'autoscaling=true'
