steps:
  - label: ':docker: Run Commtest'
    retry:
      automatic: true
    plugins:
      - docker-compose#v4.14.0:
          run: commtest
          command: ['bash', 'run-tests-ci.sh']
          config:
            - services/docker-compose.yml
            - services/docker-compose.tests.yml
          upload-container-logs: always
          build-parallel: true
    agents:
      - 'autoscaling=true'
