steps:
  - label: ":docker: Keyserver Build (Docker)"
    command:
      - 'scripts/install_protobuf.sh'
      - 'cd keyserver && touch .env && bash/dc.sh build --no-cache'
    agents:
      - 'autoscaling=true'
