steps:
  - label: 'Emscripten build'
    command:
      - 'apt update && apt install -y autoconf libtool build-essential cmake git'
      - 'cd web'
      - './scripts/run_emscripten.sh'
      - 'git diff --exit-code'
    retry:
      automatic: true
    plugins:
      - docker#v5.3.0:
          image: 'emscripten/emsdk:3.1.17'
          propagate-environment: true
    agents:
      - 'autoscaling=true'
