steps:
  - label: 'Emscripten build'
    command:
      - 'cd web'
      - 'nix develop --accept-flake-config --command yarn clean-db-wasm --command yarn build-db-wasm'
      - 'git diff --exit-code'
    retry:
      automatic: true
    agents:
      - 'mac=true'
