steps:
  - label: 'Identity Tests'
    command:
      - 'cd services/identity'
      - 'cargo test'
    retry:
      automatic: true
    plugins:
      - docker#v5.3.0:
          image: 'rust:1.74.0'
          propagate-environment: true
    agents:
      - 'autoscaling=true'
