steps:
  - label: ':ios: iOS Build'
    command:
      - 'pod repo update && yarn workspace native clean-ios'
      - 'curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y'
      - 'rustup show active-toolchain || rustup toolchain install'
      - 'source /Users/comm/.cargo/env'
      - 'yarn ci-cleaninstall'
      - 'cd native && yarn xcodebuild -workspace Comm.xcworkspace -scheme Comm -destination generic/platform=iOS -allowProvisioningUpdates'
    retry:
      automatic: true
    env:
      PROTOC: '/opt/homebrew/bin/protoc'
    agents:
      - 'mac=true'
