steps:
  - label: ':ios: iOS Build'
    command:
      - 'pod repo update && yarn workspace native clean-ios'
      - 'curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y'
      - 'source $HOME/.cargo/env'
      - 'yarn cleaninstall --frozen-lockfile --skip-optional'
      - 'cd native/ios && xcodebuild -workspace Comm.xcworkspace -scheme Comm -destination generic/platform=iOS -allowProvisioningUpdates'
    env:
      PROTOC: '/opt/homebrew/bin/protoc'
    agents:
      - 'mac=true'
