steps:
  - label: 'JSI Codegen'
    command:
      - '(pkill flow || true)'
      - 'apt update && apt install -y cmake'
      - 'curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y'
      - '. /root/.cargo/env'
      - 'yarn cleaninstall --frozen-lockfile --skip-optional --network-timeout 180000'
      - 'cd native && yarn codegen-jsi && git diff --exit-code'
    retry:
      automatic: true
    plugins:
      - docker#v3.13.0:
          image: 'node:16.13-bullseye'
          always-pull: true
          workdir: /comm
          propagate-environment: true
    agents:
      - 'autoscaling=true'
