steps:
  - label: 'JSI Codegen'
    command:
      - '(pkill flow || true)'
      - 'apt update && apt install -y cmake git'
      - 'curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y'
      - '. /root/.cargo/env'
      - 'yarn ci-cleaninstall'
      - 'cd native && yarn codegen-jsi && git diff --exit-code'
    retry:
      automatic: true
    plugins:
      - docker#v5.3.0:
          image: 'node:20.10.0-bullseye'
          always-pull: true
          workdir: /comm
          propagate-environment: true
    agents:
      - 'autoscaling=true'
