steps:
  - label: ':macos: macOS Build'
    command:
      - 'pod repo update && yarn workspace native clean-ios'
      - 'curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable'
      - 'source /Users/comm/.cargo/env'
      - 'yarn ci-cleaninstall'
      - 'cd desktop && yarn make-dev --arch universal'
    retry:
      automatic: true
    agents:
      - 'mac=true'
