steps:
  - label: ':shell: ShellCheck'
    command:
      - 'apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y shellcheck'
      - 'shopt -s globstar'
      - 'shellcheck -x -P SCRIPTDIR **/*.sh'
    retry:
      automatic: true
    plugins:
      - docker#v3.13.0:
          image: 'debian:stable'
          shell: ['/bin/bash', '-e', '-c']
          propagate-environment: true
    agents:
      - 'autoscaling=true'
