env:
  PATH: '$HOME/.nix-profile/bin:/nix/var/nix/profiles/default/bin:$PATH'
steps:
  - label: ':nix: Tunnelbroker Unittests'
    command:
      - 'cd services/tunnelbroker'
      - 'rm -rf target'
      - 'nix develop --accept-flake-config -c bash -c "cargo build && cargo test"'
    retry:
      automatic: true
    agents:
      - 'mac=true'
