env:
  PATH: '$HOME/.nix-profile/bin:/nix/var/nix/profiles/default/bin:$PATH'
steps:
  - label: ':nix: Tunnelbroker Client (Shared)'
    command:
      - 'cd shared/tunnelbroker-client'
      - 'rm -rf target'
      - 'nix develop --accept-flake-config -c cargo test'
    agents:
      - 'mac=true'
