// flow-typed signature: 1b29e5c55e66215f1c86ac2e0d31519b
// flow-typed version: <<STUB>>/redux-devtools-extension_v^2.13.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-devtools-extension'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-devtools-extension' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-devtools-extension/developmentOnly' {
  declare module.exports: any;
}

declare module 'redux-devtools-extension/logOnly' {
  declare module.exports: any;
}

declare module 'redux-devtools-extension/logOnlyInProduction' {
  declare module.exports: any;
}

declare module 'redux-devtools-extension/utils/assign' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-devtools-extension/developmentOnly.js' {
  declare module.exports: $Exports<'redux-devtools-extension/developmentOnly'>;
}
declare module 'redux-devtools-extension/index' {
  declare module.exports: $Exports<'redux-devtools-extension'>;
}
declare module 'redux-devtools-extension/index.js' {
  declare module.exports: $Exports<'redux-devtools-extension'>;
}
declare module 'redux-devtools-extension/logOnly.js' {
  declare module.exports: $Exports<'redux-devtools-extension/logOnly'>;
}
declare module 'redux-devtools-extension/logOnlyInProduction.js' {
  declare module.exports: $Exports<'redux-devtools-extension/logOnlyInProduction'>;
}
declare module 'redux-devtools-extension/utils/assign.js' {
  declare module.exports: $Exports<'redux-devtools-extension/utils/assign'>;
}
