[package]
name = "util_macros"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

[lib]
proc-macro = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
syn = "1.0"
quote = "1.0"
