[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"
tonic = "0.8"
prost = "0.11"
lazy_static = "1.4"
tokio = { version = "1.13", features = ["macros", "rt-multi-thread"] }
async-stream = "0.3.2"

[build-dependencies]
cxx-build = "1.0"
tonic-build = "0.8"

[lib]
crate-type=["staticlib"]