[package]
name = "blob_client"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0"
tokio = { version = "1.20", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1"
lazy_static = "1.4"
libc = "0.2"
tonic = "0.8"
prost = "0.11"
tracing = "0.1"
async-stream = "0.3"
anyhow = "1.0"

[build-dependencies]
cxx-build = "1.0"
tonic-build = "0.8"
regex = "1.6"

[lib]
crate-type = ["staticlib"]

[profile.release]
panic = "abort"

[profile.dev]
debug = true
panic = "abort"
