[package]
name = "blob_client"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.9"
lazy_static = "1.4.0"
libc = "0.2.132"
tonic = "0.8"
prost = "0.11"
tracing = "0.1"

[build-dependencies]
cxx-build = "1.0"
tonic-build = "0.8"
regex = "1.6.0"

[lib]
crate-type = ["staticlib"]

[profile.release]
debug = true
panic = "abort"

[profile.dev]
panic = "abort"
