// flow-typed signature: 08e97cbd87daa634b458be0e27482a10
// flow-typed version: <<STUB>>/react-html-email_v^3.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-html-email'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-html-email' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-html-email/lib/components/A' {
  declare module.exports: any;
}

declare module 'react-html-email/lib/components/Box' {
  declare module.exports: any;
}

declare module 'react-html-email/lib/components/Email' {
  declare module.exports: any;
}

declare module 'react-html-email/lib/components/Image' {
  declare module.exports: any;
}

declare module 'react-html-email/lib/components/Item' {
  declare module.exports: any;
}

declare module 'react-html-email/lib/components/Span' {
  declare module.exports: any;
}

declare module 'react-html-email/lib/includeDataProps' {
  declare module.exports: any;
}

declare module 'react-html-email/lib/index' {
  declare module.exports: any;
}

declare module 'react-html-email/lib/injectReactEmailAttributes' {
  declare module.exports: any;
}

declare module 'react-html-email/lib/PropTypes' {
  declare module.exports: any;
}

declare module 'react-html-email/lib/renderEmail' {
  declare module.exports: any;
}

declare module 'react-html-email/lib/StyleValidator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-html-email/lib/components/A.js' {
  declare module.exports: $Exports<'react-html-email/lib/components/A'>;
}
declare module 'react-html-email/lib/components/Box.js' {
  declare module.exports: $Exports<'react-html-email/lib/components/Box'>;
}
declare module 'react-html-email/lib/components/Email.js' {
  declare module.exports: $Exports<'react-html-email/lib/components/Email'>;
}
declare module 'react-html-email/lib/components/Image.js' {
  declare module.exports: $Exports<'react-html-email/lib/components/Image'>;
}
declare module 'react-html-email/lib/components/Item.js' {
  declare module.exports: $Exports<'react-html-email/lib/components/Item'>;
}
declare module 'react-html-email/lib/components/Span.js' {
  declare module.exports: $Exports<'react-html-email/lib/components/Span'>;
}
declare module 'react-html-email/lib/includeDataProps.js' {
  declare module.exports: $Exports<'react-html-email/lib/includeDataProps'>;
}
declare module 'react-html-email/lib/index.js' {
  declare module.exports: $Exports<'react-html-email/lib/index'>;
}
declare module 'react-html-email/lib/injectReactEmailAttributes.js' {
  declare module.exports: $Exports<'react-html-email/lib/injectReactEmailAttributes'>;
}
declare module 'react-html-email/lib/PropTypes.js' {
  declare module.exports: $Exports<'react-html-email/lib/PropTypes'>;
}
declare module 'react-html-email/lib/renderEmail.js' {
  declare module.exports: $Exports<'react-html-email/lib/renderEmail'>;
}
declare module 'react-html-email/lib/StyleValidator.js' {
  declare module.exports: $Exports<'react-html-email/lib/StyleValidator'>;
}
