// @generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: backup.proto

#include "backup.pb.h"
#include "backup.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace backup {

static const char* BackupService_method_names[] = {
  "/backup.BackupService/CreateNewBackup",
  "/backup.BackupService/SendLog",
  "/backup.BackupService/PullBackupKey",
  "/backup.BackupService/PullCompaction",
};

std::unique_ptr< BackupService::Stub> BackupService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< BackupService::Stub> stub(new BackupService::Stub(channel, options));
  return stub;
}

BackupService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateNewBackup_(BackupService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_SendLog_(BackupService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_PullBackupKey_(BackupService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_PullCompaction_(BackupService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientWriter< ::backup::CreateNewBackupRequest>* BackupService::Stub::CreateNewBackupRaw(::grpc::ClientContext* context, ::google::protobuf::Empty* response) {
  return ::grpc::internal::ClientWriterFactory< ::backup::CreateNewBackupRequest>::Create(channel_.get(), rpcmethod_CreateNewBackup_, context, response);
}

void BackupService::Stub::async::CreateNewBackup(::grpc::ClientContext* context, ::google::protobuf::Empty* response, ::grpc::ClientWriteReactor< ::backup::CreateNewBackupRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::backup::CreateNewBackupRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_CreateNewBackup_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::backup::CreateNewBackupRequest>* BackupService::Stub::AsyncCreateNewBackupRaw(::grpc::ClientContext* context, ::google::protobuf::Empty* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::backup::CreateNewBackupRequest>::Create(channel_.get(), cq, rpcmethod_CreateNewBackup_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::backup::CreateNewBackupRequest>* BackupService::Stub::PrepareAsyncCreateNewBackupRaw(::grpc::ClientContext* context, ::google::protobuf::Empty* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::backup::CreateNewBackupRequest>::Create(channel_.get(), cq, rpcmethod_CreateNewBackup_, context, response, false, nullptr);
}

::grpc::ClientWriter< ::backup::SendLogRequest>* BackupService::Stub::SendLogRaw(::grpc::ClientContext* context, ::google::protobuf::Empty* response) {
  return ::grpc::internal::ClientWriterFactory< ::backup::SendLogRequest>::Create(channel_.get(), rpcmethod_SendLog_, context, response);
}

void BackupService::Stub::async::SendLog(::grpc::ClientContext* context, ::google::protobuf::Empty* response, ::grpc::ClientWriteReactor< ::backup::SendLogRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::backup::SendLogRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_SendLog_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::backup::SendLogRequest>* BackupService::Stub::AsyncSendLogRaw(::grpc::ClientContext* context, ::google::protobuf::Empty* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::backup::SendLogRequest>::Create(channel_.get(), cq, rpcmethod_SendLog_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::backup::SendLogRequest>* BackupService::Stub::PrepareAsyncSendLogRaw(::grpc::ClientContext* context, ::google::protobuf::Empty* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::backup::SendLogRequest>::Create(channel_.get(), cq, rpcmethod_SendLog_, context, response, false, nullptr);
}

::grpc::ClientReaderWriter< ::backup::PullBackupKeyRequest, ::backup::PullBackupKeyResponse>* BackupService::Stub::PullBackupKeyRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::backup::PullBackupKeyRequest, ::backup::PullBackupKeyResponse>::Create(channel_.get(), rpcmethod_PullBackupKey_, context);
}

void BackupService::Stub::async::PullBackupKey(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::backup::PullBackupKeyRequest,::backup::PullBackupKeyResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::backup::PullBackupKeyRequest,::backup::PullBackupKeyResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_PullBackupKey_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::backup::PullBackupKeyRequest, ::backup::PullBackupKeyResponse>* BackupService::Stub::AsyncPullBackupKeyRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::backup::PullBackupKeyRequest, ::backup::PullBackupKeyResponse>::Create(channel_.get(), cq, rpcmethod_PullBackupKey_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::backup::PullBackupKeyRequest, ::backup::PullBackupKeyResponse>* BackupService::Stub::PrepareAsyncPullBackupKeyRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::backup::PullBackupKeyRequest, ::backup::PullBackupKeyResponse>::Create(channel_.get(), cq, rpcmethod_PullBackupKey_, context, false, nullptr);
}

::grpc::ClientReaderWriter< ::backup::PullCompactionRequest, ::backup::PullCompactionResponse>* BackupService::Stub::PullCompactionRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::backup::PullCompactionRequest, ::backup::PullCompactionResponse>::Create(channel_.get(), rpcmethod_PullCompaction_, context);
}

void BackupService::Stub::async::PullCompaction(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::backup::PullCompactionRequest,::backup::PullCompactionResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::backup::PullCompactionRequest,::backup::PullCompactionResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_PullCompaction_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::backup::PullCompactionRequest, ::backup::PullCompactionResponse>* BackupService::Stub::AsyncPullCompactionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::backup::PullCompactionRequest, ::backup::PullCompactionResponse>::Create(channel_.get(), cq, rpcmethod_PullCompaction_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::backup::PullCompactionRequest, ::backup::PullCompactionResponse>* BackupService::Stub::PrepareAsyncPullCompactionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::backup::PullCompactionRequest, ::backup::PullCompactionResponse>::Create(channel_.get(), cq, rpcmethod_PullCompaction_, context, false, nullptr);
}

BackupService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BackupService_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< BackupService::Service, ::backup::CreateNewBackupRequest, ::google::protobuf::Empty>(
          [](BackupService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::backup::CreateNewBackupRequest>* reader,
             ::google::protobuf::Empty* resp) {
               return service->CreateNewBackup(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BackupService_method_names[1],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< BackupService::Service, ::backup::SendLogRequest, ::google::protobuf::Empty>(
          [](BackupService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::backup::SendLogRequest>* reader,
             ::google::protobuf::Empty* resp) {
               return service->SendLog(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BackupService_method_names[2],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< BackupService::Service, ::backup::PullBackupKeyRequest, ::backup::PullBackupKeyResponse>(
          [](BackupService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::backup::PullBackupKeyResponse,
             ::backup::PullBackupKeyRequest>* stream) {
               return service->PullBackupKey(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BackupService_method_names[3],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< BackupService::Service, ::backup::PullCompactionRequest, ::backup::PullCompactionResponse>(
          [](BackupService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::backup::PullCompactionResponse,
             ::backup::PullCompactionRequest>* stream) {
               return service->PullCompaction(ctx, stream);
             }, this)));
}

BackupService::Service::~Service() {
}

::grpc::Status BackupService::Service::CreateNewBackup(::grpc::ServerContext* context, ::grpc::ServerReader< ::backup::CreateNewBackupRequest>* reader, ::google::protobuf::Empty* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BackupService::Service::SendLog(::grpc::ServerContext* context, ::grpc::ServerReader< ::backup::SendLogRequest>* reader, ::google::protobuf::Empty* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BackupService::Service::PullBackupKey(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::backup::PullBackupKeyResponse, ::backup::PullBackupKeyRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BackupService::Service::PullCompaction(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::backup::PullCompactionResponse, ::backup::PullCompactionRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace backup

