// flow-typed signature: fec2356f6c0acff0dc6dc8cf186276d1
// flow-typed version: <<STUB>>/express-ws_v^4.0.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-ws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-ws' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-ws/examples/broadcast' {
  declare module.exports: any;
}

declare module 'express-ws/examples/https' {
  declare module.exports: any;
}

declare module 'express-ws/examples/params' {
  declare module.exports: any;
}

declare module 'express-ws/examples/simple' {
  declare module.exports: any;
}

declare module 'express-ws/lib/add-ws-method' {
  declare module.exports: any;
}

declare module 'express-ws/lib/index' {
  declare module.exports: any;
}

declare module 'express-ws/lib/trailing-slash' {
  declare module.exports: any;
}

declare module 'express-ws/lib/websocket-url' {
  declare module.exports: any;
}

declare module 'express-ws/lib/wrap-middleware' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-ws/examples/broadcast.js' {
  declare module.exports: $Exports<'express-ws/examples/broadcast'>;
}
declare module 'express-ws/examples/https.js' {
  declare module.exports: $Exports<'express-ws/examples/https'>;
}
declare module 'express-ws/examples/params.js' {
  declare module.exports: $Exports<'express-ws/examples/params'>;
}
declare module 'express-ws/examples/simple.js' {
  declare module.exports: $Exports<'express-ws/examples/simple'>;
}
declare module 'express-ws/index' {
  declare module.exports: $Exports<'express-ws'>;
}
declare module 'express-ws/index.js' {
  declare module.exports: $Exports<'express-ws'>;
}
declare module 'express-ws/lib/add-ws-method.js' {
  declare module.exports: $Exports<'express-ws/lib/add-ws-method'>;
}
declare module 'express-ws/lib/index.js' {
  declare module.exports: $Exports<'express-ws/lib/index'>;
}
declare module 'express-ws/lib/trailing-slash.js' {
  declare module.exports: $Exports<'express-ws/lib/trailing-slash'>;
}
declare module 'express-ws/lib/websocket-url.js' {
  declare module.exports: $Exports<'express-ws/lib/websocket-url'>;
}
declare module 'express-ws/lib/wrap-middleware.js' {
  declare module.exports: $Exports<'express-ws/lib/wrap-middleware'>;
}
