// flow-typed signature: aac8dc88011f38644acb762fc3214c8a
// flow-typed version: <<STUB>>/geoip-lite_v^1.3.8/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geoip-lite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geoip-lite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'geoip-lite/lib/fsWatcher' {
  declare module.exports: any;
}

declare module 'geoip-lite/lib/geoip' {
  declare module.exports: any;
}

declare module 'geoip-lite/lib/utils' {
  declare module.exports: any;
}

declare module 'geoip-lite/scripts/updatedb' {
  declare module.exports: any;
}

declare module 'geoip-lite/test/geo-lookup' {
  declare module.exports: any;
}

declare module 'geoip-lite/test/memory_usage' {
  declare module.exports: any;
}

declare module 'geoip-lite/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'geoip-lite/lib/fsWatcher.js' {
  declare module.exports: $Exports<'geoip-lite/lib/fsWatcher'>;
}
declare module 'geoip-lite/lib/geoip.js' {
  declare module.exports: $Exports<'geoip-lite/lib/geoip'>;
}
declare module 'geoip-lite/lib/utils.js' {
  declare module.exports: $Exports<'geoip-lite/lib/utils'>;
}
declare module 'geoip-lite/scripts/updatedb.js' {
  declare module.exports: $Exports<'geoip-lite/scripts/updatedb'>;
}
declare module 'geoip-lite/test/geo-lookup.js' {
  declare module.exports: $Exports<'geoip-lite/test/geo-lookup'>;
}
declare module 'geoip-lite/test/memory_usage.js' {
  declare module.exports: $Exports<'geoip-lite/test/memory_usage'>;
}
declare module 'geoip-lite/test/tests.js' {
  declare module.exports: $Exports<'geoip-lite/test/tests'>;
}
