// flow-typed signature: 044bcbad2760cfb80755448804516dc9
// flow-typed version: <<STUB>>/stream-cache_v^0.0.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream-cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stream-cache/lib/StreamCache' {
  declare module.exports: any;
}

declare module 'stream-cache/test/test-with-child-processes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stream-cache/index' {
  declare module.exports: $Exports<'stream-cache'>;
}
declare module 'stream-cache/index.js' {
  declare module.exports: $Exports<'stream-cache'>;
}
declare module 'stream-cache/lib/StreamCache.js' {
  declare module.exports: $Exports<'stream-cache/lib/StreamCache'>;
}
declare module 'stream-cache/test/test-with-child-processes.js' {
  declare module.exports: $Exports<'stream-cache/test/test-with-child-processes'>;
}
