// flow-typed signature: 756fcfc5b0b578b28fb700a10cb8aa54
// flow-typed version: <<STUB>>/twin-bcrypt_v^2.1.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'twin-bcrypt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'twin-bcrypt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'twin-bcrypt/bin/twin-bcrypt' {
  declare module.exports: any;
}

declare module 'twin-bcrypt/demo/demo' {
  declare module.exports: any;
}

declare module 'twin-bcrypt/Gearfile' {
  declare module.exports: any;
}

declare module 'twin-bcrypt/src/twin-bcrypt' {
  declare module.exports: any;
}

declare module 'twin-bcrypt/test/node-test' {
  declare module.exports: any;
}

declare module 'twin-bcrypt/test/testsuite-api' {
  declare module.exports: any;
}

declare module 'twin-bcrypt/test/testsuite-crypt-blowfish' {
  declare module.exports: any;
}

declare module 'twin-bcrypt/test/testsuite-jbcrypt' {
  declare module.exports: any;
}

declare module 'twin-bcrypt/twin-bcrypt.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'twin-bcrypt/bin/twin-bcrypt.js' {
  declare module.exports: $Exports<'twin-bcrypt/bin/twin-bcrypt'>;
}
declare module 'twin-bcrypt/demo/demo.js' {
  declare module.exports: $Exports<'twin-bcrypt/demo/demo'>;
}
declare module 'twin-bcrypt/Gearfile.js' {
  declare module.exports: $Exports<'twin-bcrypt/Gearfile'>;
}
declare module 'twin-bcrypt/src/twin-bcrypt.js' {
  declare module.exports: $Exports<'twin-bcrypt/src/twin-bcrypt'>;
}
declare module 'twin-bcrypt/test/node-test.js' {
  declare module.exports: $Exports<'twin-bcrypt/test/node-test'>;
}
declare module 'twin-bcrypt/test/testsuite-api.js' {
  declare module.exports: $Exports<'twin-bcrypt/test/testsuite-api'>;
}
declare module 'twin-bcrypt/test/testsuite-crypt-blowfish.js' {
  declare module.exports: $Exports<'twin-bcrypt/test/testsuite-crypt-blowfish'>;
}
declare module 'twin-bcrypt/test/testsuite-jbcrypt.js' {
  declare module.exports: $Exports<'twin-bcrypt/test/testsuite-jbcrypt'>;
}
declare module 'twin-bcrypt/twin-bcrypt.min.js' {
  declare module.exports: $Exports<'twin-bcrypt/twin-bcrypt.min'>;
}
