/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#if ANDROID
#include <TurboModule.h>
#else
#include <ReactCommon/TurboModule.h>
#endif

namespace facebook {
namespace react {
class JSI_EXPORT CommCoreModuleSchemaCxxSpecJSI : public TurboModule {
protected:
  CommCoreModuleSchemaCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

public:
  virtual jsi::String
  getDraft(jsi::Runtime &rt, const jsi::String &threadID) = 0;
  virtual bool updateDraft(jsi::Runtime &rt, const jsi::Object &draft) = 0;
};

} // namespace react
} // namespace facebook
