// @flow
// flow-typed signature: f8bfa3876f1890f644b65b1ebd801ed8
// flow-typed version: <<STUB>>/electron_v22.0.0/flow_v0.182.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron' {
  declare module.exports: any;
}
