// @flow

export const endpoint = Object.freeze({
  UPDATE_ACTIVITY: 'update_activity',
  UPDATE_USER_SUBSCRIPTION: 'update_user_subscription',
  UPDATE_DEVICE_TOKEN: 'update_device_token',
  UPDATE_ACCOUNT: 'update_account',
  SEND_VERIFICATION_EMAIL: 'send_verification_email',
  SEARCH_USERS: 'search_users',
  SEND_PASSWORD_RESET_EMAIL: 'send_password_reset_email',
  CREATE_TEXT_MESSAGE: 'create_text_message',
  FETCH_ENTRIES: 'fetch_entries',
  FETCH_ENTRY_REVISIONS: 'fetch_entry_revisions',
  VERIFY_CODE: 'verify_code',
  DELETE_THREAD: 'delete_thread',
  CREATE_ENTRY: 'create_entry',
  UPDATE_ENTRY: 'update_entry',
  DELETE_ENTRY: 'delete_entry',
  RESTORE_ENTRY: 'restore_entry',
  UPDATE_ROLE: 'update_role',
  REMOVE_MEMBERS: 'remove_members',
  LEAVE_THREAD: 'leave_thread',
  UPDATE_THREAD: 'update_thread',
  CREATE_THREAD: 'create_thread',
  FETCH_MESSAGES: 'fetch_messages',
  JOIN_THREAD: 'join_thread',
  PING: 'ping',
  LOG_OUT: 'log_out',
  DELETE_ACCOUNT: 'delete_account',
  CREATE_ACCOUNT: 'create_account',
  LOG_IN: 'log_in',
  UPDATE_PASSWORD: 'update_password',
  CREATE_ERROR_REPORT: 'create_error_report',
  FETCH_ERROR_REPORT_INFOS: 'fetch_error_report_infos',
});
export type Endpoint = $Values<typeof endpoint>;
