// flow-typed signature: 8c9353451871ceaff1c2f19d380d1911
// flow-typed version: <<STUB>>/AnimatedNode_vx.x.x/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'AnimatedNode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'AnimatedNode' {
  declare module.exports: any;
}
