// flow-typed signature: 4d353c310591290cc1ecdc2d0166b0f5
// flow-typed version: <<STUB>>/crna-make-symlinks-for-yarn-workspaces_v^1.0.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'crna-make-symlinks-for-yarn-workspaces'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'crna-make-symlinks-for-yarn-workspaces' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'crna-make-symlinks-for-yarn-workspaces/index' {
  declare module.exports: $Exports<'crna-make-symlinks-for-yarn-workspaces'>;
}
declare module 'crna-make-symlinks-for-yarn-workspaces/index.js' {
  declare module.exports: $Exports<'crna-make-symlinks-for-yarn-workspaces'>;
}
