// flow-typed signature: 050fe08f165167cd18d7e3b44b2b6db7
// flow-typed version: <<STUB>>/expo-file-system_v18.1.10/flow_v0.262.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-file-system'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-file-system' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-file-system/app.plugin' {
  declare module.exports: any;
}

declare module 'expo-file-system/plugin/build/withFileSystem' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-file-system/app.plugin.js' {
  declare module.exports: $Exports<'expo-file-system/app.plugin'>;
}
declare module 'expo-file-system/plugin/build/withFileSystem.js' {
  declare module.exports: $Exports<'expo-file-system/plugin/build/withFileSystem'>;
}
