// flow-typed signature: 8db5f3d6f2a6c1c497a9ea589b2e0362
// flow-typed version: <<STUB>>/fbjs_v0.8.14/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fbjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fbjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fbjs/flow/lib/dev' {
  declare module.exports: any;
}

declare module 'fbjs/lib/__mocks__/base62' {
  declare module.exports: any;
}

declare module 'fbjs/lib/__mocks__/crc32' {
  declare module.exports: any;
}

declare module 'fbjs/lib/__mocks__/ErrorUtils' {
  declare module.exports: any;
}

declare module 'fbjs/lib/__mocks__/fetch' {
  declare module.exports: any;
}

declare module 'fbjs/lib/__mocks__/fetchWithRetries' {
  declare module.exports: any;
}

declare module 'fbjs/lib/__mocks__/nullthrows' {
  declare module.exports: any;
}

declare module 'fbjs/lib/_shouldPolyfillES6Collection' {
  declare module.exports: any;
}

declare module 'fbjs/lib/areEqual' {
  declare module.exports: any;
}

declare module 'fbjs/lib/base62' {
  declare module.exports: any;
}

declare module 'fbjs/lib/camelize' {
  declare module.exports: any;
}

declare module 'fbjs/lib/camelizeStyleName' {
  declare module.exports: any;
}

declare module 'fbjs/lib/compactArray' {
  declare module.exports: any;
}

declare module 'fbjs/lib/concatAllArray' {
  declare module.exports: any;
}

declare module 'fbjs/lib/containsNode' {
  declare module.exports: any;
}

declare module 'fbjs/lib/countDistinct' {
  declare module.exports: any;
}

declare module 'fbjs/lib/crc32' {
  declare module.exports: any;
}

declare module 'fbjs/lib/createArrayFromMixed' {
  declare module.exports: any;
}

declare module 'fbjs/lib/createNodesFromMarkup' {
  declare module.exports: any;
}

declare module 'fbjs/lib/CSSCore' {
  declare module.exports: any;
}

declare module 'fbjs/lib/cx' {
  declare module.exports: any;
}

declare module 'fbjs/lib/DataTransfer' {
  declare module.exports: any;
}

declare module 'fbjs/lib/Deferred' {
  declare module.exports: any;
}

declare module 'fbjs/lib/distinctArray' {
  declare module.exports: any;
}

declare module 'fbjs/lib/emptyFunction' {
  declare module.exports: any;
}

declare module 'fbjs/lib/emptyObject' {
  declare module.exports: any;
}

declare module 'fbjs/lib/enumerate' {
  declare module.exports: any;
}

declare module 'fbjs/lib/equalsIterable' {
  declare module.exports: any;
}

declare module 'fbjs/lib/equalsSet' {
  declare module.exports: any;
}

declare module 'fbjs/lib/ErrorUtils' {
  declare module.exports: any;
}

declare module 'fbjs/lib/EventListener' {
  declare module.exports: any;
}

declare module 'fbjs/lib/everyObject' {
  declare module.exports: any;
}

declare module 'fbjs/lib/everySet' {
  declare module.exports: any;
}

declare module 'fbjs/lib/ExecutionEnvironment' {
  declare module.exports: any;
}

declare module 'fbjs/lib/fetch' {
  declare module.exports: any;
}

declare module 'fbjs/lib/fetchWithRetries' {
  declare module.exports: any;
}

declare module 'fbjs/lib/filterObject' {
  declare module.exports: any;
}

declare module 'fbjs/lib/flatMapArray' {
  declare module.exports: any;
}

declare module 'fbjs/lib/flattenArray' {
  declare module.exports: any;
}

declare module 'fbjs/lib/focusNode' {
  declare module.exports: any;
}

declare module 'fbjs/lib/forEachObject' {
  declare module.exports: any;
}

declare module 'fbjs/lib/getActiveElement' {
  declare module.exports: any;
}

declare module 'fbjs/lib/getDocumentScrollElement' {
  declare module.exports: any;
}

declare module 'fbjs/lib/getElementPosition' {
  declare module.exports: any;
}

declare module 'fbjs/lib/getElementRect' {
  declare module.exports: any;
}

declare module 'fbjs/lib/getMarkupWrap' {
  declare module.exports: any;
}

declare module 'fbjs/lib/getScrollPosition' {
  declare module.exports: any;
}

declare module 'fbjs/lib/getStyleProperty' {
  declare module.exports: any;
}

declare module 'fbjs/lib/getUnboundedScrollPosition' {
  declare module.exports: any;
}

declare module 'fbjs/lib/getViewportDimensions' {
  declare module.exports: any;
}

declare module 'fbjs/lib/groupArray' {
  declare module.exports: any;
}

declare module 'fbjs/lib/hyphenate' {
  declare module.exports: any;
}

declare module 'fbjs/lib/hyphenateStyleName' {
  declare module.exports: any;
}

declare module 'fbjs/lib/invariant' {
  declare module.exports: any;
}

declare module 'fbjs/lib/isEmpty' {
  declare module.exports: any;
}

declare module 'fbjs/lib/isNode' {
  declare module.exports: any;
}

declare module 'fbjs/lib/isTextNode' {
  declare module.exports: any;
}

declare module 'fbjs/lib/joinClasses' {
  declare module.exports: any;
}

declare module 'fbjs/lib/keyMirror' {
  declare module.exports: any;
}

declare module 'fbjs/lib/keyMirrorRecursive' {
  declare module.exports: any;
}

declare module 'fbjs/lib/keyOf' {
  declare module.exports: any;
}

declare module 'fbjs/lib/Keys' {
  declare module.exports: any;
}

declare module 'fbjs/lib/Map' {
  declare module.exports: any;
}

declare module 'fbjs/lib/mapObject' {
  declare module.exports: any;
}

declare module 'fbjs/lib/maxBy' {
  declare module.exports: any;
}

declare module 'fbjs/lib/memoizeStringOnly' {
  declare module.exports: any;
}

declare module 'fbjs/lib/minBy' {
  declare module.exports: any;
}

declare module 'fbjs/lib/monitorCodeUse' {
  declare module.exports: any;
}

declare module 'fbjs/lib/nativeRequestAnimationFrame' {
  declare module.exports: any;
}

declare module 'fbjs/lib/nullthrows' {
  declare module.exports: any;
}

declare module 'fbjs/lib/partitionArray' {
  declare module.exports: any;
}

declare module 'fbjs/lib/partitionObject' {
  declare module.exports: any;
}

declare module 'fbjs/lib/partitionObjectByKey' {
  declare module.exports: any;
}

declare module 'fbjs/lib/performance' {
  declare module.exports: any;
}

declare module 'fbjs/lib/performanceNow' {
  declare module.exports: any;
}

declare module 'fbjs/lib/PhotosMimeType' {
  declare module.exports: any;
}

declare module 'fbjs/lib/Promise' {
  declare module.exports: any;
}

declare module 'fbjs/lib/Promise.native' {
  declare module.exports: any;
}

declare module 'fbjs/lib/PromiseMap' {
  declare module.exports: any;
}

declare module 'fbjs/lib/removeFromArray' {
  declare module.exports: any;
}

declare module 'fbjs/lib/requestAnimationFrame' {
  declare module.exports: any;
}

declare module 'fbjs/lib/resolveImmediate' {
  declare module.exports: any;
}

declare module 'fbjs/lib/Scroll' {
  declare module.exports: any;
}

declare module 'fbjs/lib/Set' {
  declare module.exports: any;
}

declare module 'fbjs/lib/setImmediate' {
  declare module.exports: any;
}

declare module 'fbjs/lib/shallowEqual' {
  declare module.exports: any;
}

declare module 'fbjs/lib/someObject' {
  declare module.exports: any;
}

declare module 'fbjs/lib/someSet' {
  declare module.exports: any;
}

declare module 'fbjs/lib/sprintf' {
  declare module.exports: any;
}

declare module 'fbjs/lib/Style' {
  declare module.exports: any;
}

declare module 'fbjs/lib/TokenizeUtil' {
  declare module.exports: any;
}

declare module 'fbjs/lib/TouchEventUtils' {
  declare module.exports: any;
}

declare module 'fbjs/lib/UnicodeBidi' {
  declare module.exports: any;
}

declare module 'fbjs/lib/UnicodeBidiDirection' {
  declare module.exports: any;
}

declare module 'fbjs/lib/UnicodeBidiService' {
  declare module.exports: any;
}

declare module 'fbjs/lib/UnicodeCJK' {
  declare module.exports: any;
}

declare module 'fbjs/lib/UnicodeHangulKorean' {
  declare module.exports: any;
}

declare module 'fbjs/lib/UnicodeUtils' {
  declare module.exports: any;
}

declare module 'fbjs/lib/UnicodeUtilsExtra' {
  declare module.exports: any;
}

declare module 'fbjs/lib/URI' {
  declare module.exports: any;
}

declare module 'fbjs/lib/UserAgent' {
  declare module.exports: any;
}

declare module 'fbjs/lib/UserAgentData' {
  declare module.exports: any;
}

declare module 'fbjs/lib/VersionRange' {
  declare module.exports: any;
}

declare module 'fbjs/lib/warning' {
  declare module.exports: any;
}

declare module 'fbjs/lib/xhrSimpleDataSerializer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fbjs/flow/lib/dev.js' {
  declare module.exports: $Exports<'fbjs/flow/lib/dev'>;
}
declare module 'fbjs/index' {
  declare module.exports: $Exports<'fbjs'>;
}
declare module 'fbjs/index.js' {
  declare module.exports: $Exports<'fbjs'>;
}
declare module 'fbjs/lib/__mocks__/base62.js' {
  declare module.exports: $Exports<'fbjs/lib/__mocks__/base62'>;
}
declare module 'fbjs/lib/__mocks__/crc32.js' {
  declare module.exports: $Exports<'fbjs/lib/__mocks__/crc32'>;
}
declare module 'fbjs/lib/__mocks__/ErrorUtils.js' {
  declare module.exports: $Exports<'fbjs/lib/__mocks__/ErrorUtils'>;
}
declare module 'fbjs/lib/__mocks__/fetch.js' {
  declare module.exports: $Exports<'fbjs/lib/__mocks__/fetch'>;
}
declare module 'fbjs/lib/__mocks__/fetchWithRetries.js' {
  declare module.exports: $Exports<'fbjs/lib/__mocks__/fetchWithRetries'>;
}
declare module 'fbjs/lib/__mocks__/nullthrows.js' {
  declare module.exports: $Exports<'fbjs/lib/__mocks__/nullthrows'>;
}
declare module 'fbjs/lib/_shouldPolyfillES6Collection.js' {
  declare module.exports: $Exports<'fbjs/lib/_shouldPolyfillES6Collection'>;
}
declare module 'fbjs/lib/areEqual.js' {
  declare module.exports: $Exports<'fbjs/lib/areEqual'>;
}
declare module 'fbjs/lib/base62.js' {
  declare module.exports: $Exports<'fbjs/lib/base62'>;
}
declare module 'fbjs/lib/camelize.js' {
  declare module.exports: $Exports<'fbjs/lib/camelize'>;
}
declare module 'fbjs/lib/camelizeStyleName.js' {
  declare module.exports: $Exports<'fbjs/lib/camelizeStyleName'>;
}
declare module 'fbjs/lib/compactArray.js' {
  declare module.exports: $Exports<'fbjs/lib/compactArray'>;
}
declare module 'fbjs/lib/concatAllArray.js' {
  declare module.exports: $Exports<'fbjs/lib/concatAllArray'>;
}
declare module 'fbjs/lib/containsNode.js' {
  declare module.exports: $Exports<'fbjs/lib/containsNode'>;
}
declare module 'fbjs/lib/countDistinct.js' {
  declare module.exports: $Exports<'fbjs/lib/countDistinct'>;
}
declare module 'fbjs/lib/crc32.js' {
  declare module.exports: $Exports<'fbjs/lib/crc32'>;
}
declare module 'fbjs/lib/createArrayFromMixed.js' {
  declare module.exports: $Exports<'fbjs/lib/createArrayFromMixed'>;
}
declare module 'fbjs/lib/createNodesFromMarkup.js' {
  declare module.exports: $Exports<'fbjs/lib/createNodesFromMarkup'>;
}
declare module 'fbjs/lib/CSSCore.js' {
  declare module.exports: $Exports<'fbjs/lib/CSSCore'>;
}
declare module 'fbjs/lib/cx.js' {
  declare module.exports: $Exports<'fbjs/lib/cx'>;
}
declare module 'fbjs/lib/DataTransfer.js' {
  declare module.exports: $Exports<'fbjs/lib/DataTransfer'>;
}
declare module 'fbjs/lib/Deferred.js' {
  declare module.exports: $Exports<'fbjs/lib/Deferred'>;
}
declare module 'fbjs/lib/distinctArray.js' {
  declare module.exports: $Exports<'fbjs/lib/distinctArray'>;
}
declare module 'fbjs/lib/emptyFunction.js' {
  declare module.exports: $Exports<'fbjs/lib/emptyFunction'>;
}
declare module 'fbjs/lib/emptyObject.js' {
  declare module.exports: $Exports<'fbjs/lib/emptyObject'>;
}
declare module 'fbjs/lib/enumerate.js' {
  declare module.exports: $Exports<'fbjs/lib/enumerate'>;
}
declare module 'fbjs/lib/equalsIterable.js' {
  declare module.exports: $Exports<'fbjs/lib/equalsIterable'>;
}
declare module 'fbjs/lib/equalsSet.js' {
  declare module.exports: $Exports<'fbjs/lib/equalsSet'>;
}
declare module 'fbjs/lib/ErrorUtils.js' {
  declare module.exports: $Exports<'fbjs/lib/ErrorUtils'>;
}
declare module 'fbjs/lib/EventListener.js' {
  declare module.exports: $Exports<'fbjs/lib/EventListener'>;
}
declare module 'fbjs/lib/everyObject.js' {
  declare module.exports: $Exports<'fbjs/lib/everyObject'>;
}
declare module 'fbjs/lib/everySet.js' {
  declare module.exports: $Exports<'fbjs/lib/everySet'>;
}
declare module 'fbjs/lib/ExecutionEnvironment.js' {
  declare module.exports: $Exports<'fbjs/lib/ExecutionEnvironment'>;
}
declare module 'fbjs/lib/fetch.js' {
  declare module.exports: $Exports<'fbjs/lib/fetch'>;
}
declare module 'fbjs/lib/fetchWithRetries.js' {
  declare module.exports: $Exports<'fbjs/lib/fetchWithRetries'>;
}
declare module 'fbjs/lib/filterObject.js' {
  declare module.exports: $Exports<'fbjs/lib/filterObject'>;
}
declare module 'fbjs/lib/flatMapArray.js' {
  declare module.exports: $Exports<'fbjs/lib/flatMapArray'>;
}
declare module 'fbjs/lib/flattenArray.js' {
  declare module.exports: $Exports<'fbjs/lib/flattenArray'>;
}
declare module 'fbjs/lib/focusNode.js' {
  declare module.exports: $Exports<'fbjs/lib/focusNode'>;
}
declare module 'fbjs/lib/forEachObject.js' {
  declare module.exports: $Exports<'fbjs/lib/forEachObject'>;
}
declare module 'fbjs/lib/getActiveElement.js' {
  declare module.exports: $Exports<'fbjs/lib/getActiveElement'>;
}
declare module 'fbjs/lib/getDocumentScrollElement.js' {
  declare module.exports: $Exports<'fbjs/lib/getDocumentScrollElement'>;
}
declare module 'fbjs/lib/getElementPosition.js' {
  declare module.exports: $Exports<'fbjs/lib/getElementPosition'>;
}
declare module 'fbjs/lib/getElementRect.js' {
  declare module.exports: $Exports<'fbjs/lib/getElementRect'>;
}
declare module 'fbjs/lib/getMarkupWrap.js' {
  declare module.exports: $Exports<'fbjs/lib/getMarkupWrap'>;
}
declare module 'fbjs/lib/getScrollPosition.js' {
  declare module.exports: $Exports<'fbjs/lib/getScrollPosition'>;
}
declare module 'fbjs/lib/getStyleProperty.js' {
  declare module.exports: $Exports<'fbjs/lib/getStyleProperty'>;
}
declare module 'fbjs/lib/getUnboundedScrollPosition.js' {
  declare module.exports: $Exports<'fbjs/lib/getUnboundedScrollPosition'>;
}
declare module 'fbjs/lib/getViewportDimensions.js' {
  declare module.exports: $Exports<'fbjs/lib/getViewportDimensions'>;
}
declare module 'fbjs/lib/groupArray.js' {
  declare module.exports: $Exports<'fbjs/lib/groupArray'>;
}
declare module 'fbjs/lib/hyphenate.js' {
  declare module.exports: $Exports<'fbjs/lib/hyphenate'>;
}
declare module 'fbjs/lib/hyphenateStyleName.js' {
  declare module.exports: $Exports<'fbjs/lib/hyphenateStyleName'>;
}
declare module 'fbjs/lib/invariant.js' {
  declare module.exports: $Exports<'fbjs/lib/invariant'>;
}
declare module 'fbjs/lib/isEmpty.js' {
  declare module.exports: $Exports<'fbjs/lib/isEmpty'>;
}
declare module 'fbjs/lib/isNode.js' {
  declare module.exports: $Exports<'fbjs/lib/isNode'>;
}
declare module 'fbjs/lib/isTextNode.js' {
  declare module.exports: $Exports<'fbjs/lib/isTextNode'>;
}
declare module 'fbjs/lib/joinClasses.js' {
  declare module.exports: $Exports<'fbjs/lib/joinClasses'>;
}
declare module 'fbjs/lib/keyMirror.js' {
  declare module.exports: $Exports<'fbjs/lib/keyMirror'>;
}
declare module 'fbjs/lib/keyMirrorRecursive.js' {
  declare module.exports: $Exports<'fbjs/lib/keyMirrorRecursive'>;
}
declare module 'fbjs/lib/keyOf.js' {
  declare module.exports: $Exports<'fbjs/lib/keyOf'>;
}
declare module 'fbjs/lib/Keys.js' {
  declare module.exports: $Exports<'fbjs/lib/Keys'>;
}
declare module 'fbjs/lib/Map.js' {
  declare module.exports: $Exports<'fbjs/lib/Map'>;
}
declare module 'fbjs/lib/mapObject.js' {
  declare module.exports: $Exports<'fbjs/lib/mapObject'>;
}
declare module 'fbjs/lib/maxBy.js' {
  declare module.exports: $Exports<'fbjs/lib/maxBy'>;
}
declare module 'fbjs/lib/memoizeStringOnly.js' {
  declare module.exports: $Exports<'fbjs/lib/memoizeStringOnly'>;
}
declare module 'fbjs/lib/minBy.js' {
  declare module.exports: $Exports<'fbjs/lib/minBy'>;
}
declare module 'fbjs/lib/monitorCodeUse.js' {
  declare module.exports: $Exports<'fbjs/lib/monitorCodeUse'>;
}
declare module 'fbjs/lib/nativeRequestAnimationFrame.js' {
  declare module.exports: $Exports<'fbjs/lib/nativeRequestAnimationFrame'>;
}
declare module 'fbjs/lib/nullthrows.js' {
  declare module.exports: $Exports<'fbjs/lib/nullthrows'>;
}
declare module 'fbjs/lib/partitionArray.js' {
  declare module.exports: $Exports<'fbjs/lib/partitionArray'>;
}
declare module 'fbjs/lib/partitionObject.js' {
  declare module.exports: $Exports<'fbjs/lib/partitionObject'>;
}
declare module 'fbjs/lib/partitionObjectByKey.js' {
  declare module.exports: $Exports<'fbjs/lib/partitionObjectByKey'>;
}
declare module 'fbjs/lib/performance.js' {
  declare module.exports: $Exports<'fbjs/lib/performance'>;
}
declare module 'fbjs/lib/performanceNow.js' {
  declare module.exports: $Exports<'fbjs/lib/performanceNow'>;
}
declare module 'fbjs/lib/PhotosMimeType.js' {
  declare module.exports: $Exports<'fbjs/lib/PhotosMimeType'>;
}
declare module 'fbjs/lib/Promise.js' {
  declare module.exports: $Exports<'fbjs/lib/Promise'>;
}
declare module 'fbjs/lib/Promise.native.js' {
  declare module.exports: $Exports<'fbjs/lib/Promise.native'>;
}
declare module 'fbjs/lib/PromiseMap.js' {
  declare module.exports: $Exports<'fbjs/lib/PromiseMap'>;
}
declare module 'fbjs/lib/removeFromArray.js' {
  declare module.exports: $Exports<'fbjs/lib/removeFromArray'>;
}
declare module 'fbjs/lib/requestAnimationFrame.js' {
  declare module.exports: $Exports<'fbjs/lib/requestAnimationFrame'>;
}
declare module 'fbjs/lib/resolveImmediate.js' {
  declare module.exports: $Exports<'fbjs/lib/resolveImmediate'>;
}
declare module 'fbjs/lib/Scroll.js' {
  declare module.exports: $Exports<'fbjs/lib/Scroll'>;
}
declare module 'fbjs/lib/Set.js' {
  declare module.exports: $Exports<'fbjs/lib/Set'>;
}
declare module 'fbjs/lib/setImmediate.js' {
  declare module.exports: $Exports<'fbjs/lib/setImmediate'>;
}
declare module 'fbjs/lib/shallowEqual.js' {
  declare module.exports: $Exports<'fbjs/lib/shallowEqual'>;
}
declare module 'fbjs/lib/someObject.js' {
  declare module.exports: $Exports<'fbjs/lib/someObject'>;
}
declare module 'fbjs/lib/someSet.js' {
  declare module.exports: $Exports<'fbjs/lib/someSet'>;
}
declare module 'fbjs/lib/sprintf.js' {
  declare module.exports: $Exports<'fbjs/lib/sprintf'>;
}
declare module 'fbjs/lib/Style.js' {
  declare module.exports: $Exports<'fbjs/lib/Style'>;
}
declare module 'fbjs/lib/TokenizeUtil.js' {
  declare module.exports: $Exports<'fbjs/lib/TokenizeUtil'>;
}
declare module 'fbjs/lib/TouchEventUtils.js' {
  declare module.exports: $Exports<'fbjs/lib/TouchEventUtils'>;
}
declare module 'fbjs/lib/UnicodeBidi.js' {
  declare module.exports: $Exports<'fbjs/lib/UnicodeBidi'>;
}
declare module 'fbjs/lib/UnicodeBidiDirection.js' {
  declare module.exports: $Exports<'fbjs/lib/UnicodeBidiDirection'>;
}
declare module 'fbjs/lib/UnicodeBidiService.js' {
  declare module.exports: $Exports<'fbjs/lib/UnicodeBidiService'>;
}
declare module 'fbjs/lib/UnicodeCJK.js' {
  declare module.exports: $Exports<'fbjs/lib/UnicodeCJK'>;
}
declare module 'fbjs/lib/UnicodeHangulKorean.js' {
  declare module.exports: $Exports<'fbjs/lib/UnicodeHangulKorean'>;
}
declare module 'fbjs/lib/UnicodeUtils.js' {
  declare module.exports: $Exports<'fbjs/lib/UnicodeUtils'>;
}
declare module 'fbjs/lib/UnicodeUtilsExtra.js' {
  declare module.exports: $Exports<'fbjs/lib/UnicodeUtilsExtra'>;
}
declare module 'fbjs/lib/URI.js' {
  declare module.exports: $Exports<'fbjs/lib/URI'>;
}
declare module 'fbjs/lib/UserAgent.js' {
  declare module.exports: $Exports<'fbjs/lib/UserAgent'>;
}
declare module 'fbjs/lib/UserAgentData.js' {
  declare module.exports: $Exports<'fbjs/lib/UserAgentData'>;
}
declare module 'fbjs/lib/VersionRange.js' {
  declare module.exports: $Exports<'fbjs/lib/VersionRange'>;
}
declare module 'fbjs/lib/warning.js' {
  declare module.exports: $Exports<'fbjs/lib/warning'>;
}
declare module 'fbjs/lib/xhrSimpleDataSerializer.js' {
  declare module.exports: $Exports<'fbjs/lib/xhrSimpleDataSerializer'>;
}
