// flow-typed signature: 903ed7120a6dbe47f7488572ba44ddad
// flow-typed version: <<STUB>>/react-native-keychain_v^1.2.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-keychain'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-keychain' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-keychain/index' {
  declare module.exports: $Exports<'react-native-keychain'>;
}
declare module 'react-native-keychain/index.js' {
  declare module.exports: $Exports<'react-native-keychain'>;
}
