// flow-typed signature: b0c34bf0f42f117cf446d5782a5155e7
// flow-typed version: <<STUB>>/react-native-progress_v^3.6.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-progress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-progress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-progress/Bar' {
  declare module.exports: any;
}

declare module 'react-native-progress/Circle' {
  declare module.exports: any;
}

declare module 'react-native-progress/CircleSnail' {
  declare module.exports: any;
}

declare module 'react-native-progress/Pie' {
  declare module.exports: any;
}

declare module 'react-native-progress/Shapes/Arc' {
  declare module.exports: any;
}

declare module 'react-native-progress/Shapes/Circle' {
  declare module.exports: any;
}

declare module 'react-native-progress/Shapes/Sector' {
  declare module.exports: any;
}

declare module 'react-native-progress/withAnimation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-progress/Bar.js' {
  declare module.exports: $Exports<'react-native-progress/Bar'>;
}
declare module 'react-native-progress/Circle.js' {
  declare module.exports: $Exports<'react-native-progress/Circle'>;
}
declare module 'react-native-progress/CircleSnail.js' {
  declare module.exports: $Exports<'react-native-progress/CircleSnail'>;
}
declare module 'react-native-progress/index' {
  declare module.exports: $Exports<'react-native-progress'>;
}
declare module 'react-native-progress/index.js' {
  declare module.exports: $Exports<'react-native-progress'>;
}
declare module 'react-native-progress/Pie.js' {
  declare module.exports: $Exports<'react-native-progress/Pie'>;
}
declare module 'react-native-progress/Shapes/Arc.js' {
  declare module.exports: $Exports<'react-native-progress/Shapes/Arc'>;
}
declare module 'react-native-progress/Shapes/Circle.js' {
  declare module.exports: $Exports<'react-native-progress/Shapes/Circle'>;
}
declare module 'react-native-progress/Shapes/Sector.js' {
  declare module.exports: $Exports<'react-native-progress/Shapes/Sector'>;
}
declare module 'react-native-progress/withAnimation.js' {
  declare module.exports: $Exports<'react-native-progress/withAnimation'>;
}
