// flow-typed signature: e875bb6ae60ff2574284bd40cbf640bd
// flow-typed version: <<STUB>>/react-native-segmented-control-tab_vgit+https://github.com/ashoat/react-native-segmented-control-tab.git/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-segmented-control-tab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-segmented-control-tab' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-segmented-control-tab/SegmentedControlTab' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-segmented-control-tab/SegmentedControlTab.js' {
  declare module.exports: $Exports<'react-native-segmented-control-tab/SegmentedControlTab'>;
}
