// flow-typed signature: bd83f63588175bf0a42daf36a1857554
// flow-typed version: <<STUB>>/react-native-camera_v3.8.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-camera'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-camera' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-camera/src/FaceDetector' {
  declare module.exports: any;
}

declare module 'react-native-camera/src' {
  declare module.exports: any;
}

declare module 'react-native-camera/src/RNCamera' {
  declare module.exports: any;
}

declare module 'react-native-camera/website/core/Footer' {
  declare module.exports: any;
}

declare module 'react-native-camera/website/pages/en/help' {
  declare module.exports: any;
}

declare module 'react-native-camera/website/pages/en' {
  declare module.exports: any;
}

declare module 'react-native-camera/website/pages/en/users' {
  declare module.exports: any;
}

declare module 'react-native-camera/website/siteConfig' {
  declare module.exports: any;
}

declare module 'react-native-camera/website/static/js/code-blocks-buttons' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-camera/src/FaceDetector.js' {
  declare module.exports: $Exports<'react-native-camera/src/FaceDetector'>;
}
declare module 'react-native-camera/src/index' {
  declare module.exports: $Exports<'react-native-camera/src'>;
}
declare module 'react-native-camera/src/index.js' {
  declare module.exports: $Exports<'react-native-camera/src'>;
}
declare module 'react-native-camera/src/RNCamera.js' {
  declare module.exports: $Exports<'react-native-camera/src/RNCamera'>;
}
declare module 'react-native-camera/website/core/Footer.js' {
  declare module.exports: $Exports<'react-native-camera/website/core/Footer'>;
}
declare module 'react-native-camera/website/pages/en/help.js' {
  declare module.exports: $Exports<'react-native-camera/website/pages/en/help'>;
}
declare module 'react-native-camera/website/pages/en/index' {
  declare module.exports: $Exports<'react-native-camera/website/pages/en'>;
}
declare module 'react-native-camera/website/pages/en/index.js' {
  declare module.exports: $Exports<'react-native-camera/website/pages/en'>;
}
declare module 'react-native-camera/website/pages/en/users.js' {
  declare module.exports: $Exports<'react-native-camera/website/pages/en/users'>;
}
declare module 'react-native-camera/website/siteConfig.js' {
  declare module.exports: $Exports<'react-native-camera/website/siteConfig'>;
}
declare module 'react-native-camera/website/static/js/code-blocks-buttons.js' {
  declare module.exports: $Exports<'react-native-camera/website/static/js/code-blocks-buttons'>;
}
