// flow-typed signature: f05b2381804ff15dbb8a425b84f323f3
// flow-typed version: <<STUB>>/react-native-gesture-handler_v^1.0.10/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-gesture-handler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-gesture-handler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-gesture-handler/DrawerLayout' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/GestureHandler' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/gestureHandlerRootHOC.android' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/gestureHandlerRootHOC.ios' {
  declare module.exports: any;
}

declare module 'react-native-gesture-handler/Swipeable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-gesture-handler/DrawerLayout.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/DrawerLayout'>;
}
declare module 'react-native-gesture-handler/GestureHandler.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/GestureHandler'>;
}
declare module 'react-native-gesture-handler/gestureHandlerRootHOC.android.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/gestureHandlerRootHOC.android'>;
}
declare module 'react-native-gesture-handler/gestureHandlerRootHOC.ios.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/gestureHandlerRootHOC.ios'>;
}
declare module 'react-native-gesture-handler/index' {
  declare module.exports: $Exports<'react-native-gesture-handler'>;
}
declare module 'react-native-gesture-handler/index.js' {
  declare module.exports: $Exports<'react-native-gesture-handler'>;
}
declare module 'react-native-gesture-handler/Swipeable.js' {
  declare module.exports: $Exports<'react-native-gesture-handler/Swipeable'>;
}
