// flow-typed signature: 3db989c787f1398502458adc8b7db5a0
// flow-typed version: <<STUB>>/react-native-svg_v^9.5.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-svg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-svg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-svg/elements/Circle' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/ClipPath' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/Defs' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/Ellipse' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/G' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/Image' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/Line' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/LinearGradient' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/Mask' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/Path' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/Pattern' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/Polygon' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/Polyline' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/RadialGradient' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/Rect' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/Shape' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/Stop' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/Svg' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/Symbol' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/Text' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/TextPath' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/TSpan' {
  declare module.exports: any;
}

declare module 'react-native-svg/elements/Use' {
  declare module.exports: any;
}

declare module 'react-native-svg/index.web' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/extract/extractBrush' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/extract/extractClipPath' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/extract/extractColor' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/extract/extractFill' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/extract/extractGradient' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/extract/extractLengthList' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/extract/extractOpacity' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/extract/extractPolyPoints' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/extract/extractProps' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/extract/extractResponder' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/extract/extractStroke' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/extract/extractText' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/extract/extractTransform' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/extract/extractViewBox' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/extract/transform' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/Matrix2D' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/resolve' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/SvgTouchableMixin' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/units' {
  declare module.exports: any;
}

declare module 'react-native-svg/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-svg/elements/Circle.js' {
  declare module.exports: $Exports<'react-native-svg/elements/Circle'>;
}
declare module 'react-native-svg/elements/ClipPath.js' {
  declare module.exports: $Exports<'react-native-svg/elements/ClipPath'>;
}
declare module 'react-native-svg/elements/Defs.js' {
  declare module.exports: $Exports<'react-native-svg/elements/Defs'>;
}
declare module 'react-native-svg/elements/Ellipse.js' {
  declare module.exports: $Exports<'react-native-svg/elements/Ellipse'>;
}
declare module 'react-native-svg/elements/G.js' {
  declare module.exports: $Exports<'react-native-svg/elements/G'>;
}
declare module 'react-native-svg/elements/Image.js' {
  declare module.exports: $Exports<'react-native-svg/elements/Image'>;
}
declare module 'react-native-svg/elements/Line.js' {
  declare module.exports: $Exports<'react-native-svg/elements/Line'>;
}
declare module 'react-native-svg/elements/LinearGradient.js' {
  declare module.exports: $Exports<'react-native-svg/elements/LinearGradient'>;
}
declare module 'react-native-svg/elements/Mask.js' {
  declare module.exports: $Exports<'react-native-svg/elements/Mask'>;
}
declare module 'react-native-svg/elements/Path.js' {
  declare module.exports: $Exports<'react-native-svg/elements/Path'>;
}
declare module 'react-native-svg/elements/Pattern.js' {
  declare module.exports: $Exports<'react-native-svg/elements/Pattern'>;
}
declare module 'react-native-svg/elements/Polygon.js' {
  declare module.exports: $Exports<'react-native-svg/elements/Polygon'>;
}
declare module 'react-native-svg/elements/Polyline.js' {
  declare module.exports: $Exports<'react-native-svg/elements/Polyline'>;
}
declare module 'react-native-svg/elements/RadialGradient.js' {
  declare module.exports: $Exports<'react-native-svg/elements/RadialGradient'>;
}
declare module 'react-native-svg/elements/Rect.js' {
  declare module.exports: $Exports<'react-native-svg/elements/Rect'>;
}
declare module 'react-native-svg/elements/Shape.js' {
  declare module.exports: $Exports<'react-native-svg/elements/Shape'>;
}
declare module 'react-native-svg/elements/Stop.js' {
  declare module.exports: $Exports<'react-native-svg/elements/Stop'>;
}
declare module 'react-native-svg/elements/Svg.js' {
  declare module.exports: $Exports<'react-native-svg/elements/Svg'>;
}
declare module 'react-native-svg/elements/Symbol.js' {
  declare module.exports: $Exports<'react-native-svg/elements/Symbol'>;
}
declare module 'react-native-svg/elements/Text.js' {
  declare module.exports: $Exports<'react-native-svg/elements/Text'>;
}
declare module 'react-native-svg/elements/TextPath.js' {
  declare module.exports: $Exports<'react-native-svg/elements/TextPath'>;
}
declare module 'react-native-svg/elements/TSpan.js' {
  declare module.exports: $Exports<'react-native-svg/elements/TSpan'>;
}
declare module 'react-native-svg/elements/Use.js' {
  declare module.exports: $Exports<'react-native-svg/elements/Use'>;
}
declare module 'react-native-svg/index' {
  declare module.exports: $Exports<'react-native-svg'>;
}
declare module 'react-native-svg/index.js' {
  declare module.exports: $Exports<'react-native-svg'>;
}
declare module 'react-native-svg/index.web.js' {
  declare module.exports: $Exports<'react-native-svg/index.web'>;
}
declare module 'react-native-svg/lib/extract/extractBrush.js' {
  declare module.exports: $Exports<'react-native-svg/lib/extract/extractBrush'>;
}
declare module 'react-native-svg/lib/extract/extractClipPath.js' {
  declare module.exports: $Exports<'react-native-svg/lib/extract/extractClipPath'>;
}
declare module 'react-native-svg/lib/extract/extractColor.js' {
  declare module.exports: $Exports<'react-native-svg/lib/extract/extractColor'>;
}
declare module 'react-native-svg/lib/extract/extractFill.js' {
  declare module.exports: $Exports<'react-native-svg/lib/extract/extractFill'>;
}
declare module 'react-native-svg/lib/extract/extractGradient.js' {
  declare module.exports: $Exports<'react-native-svg/lib/extract/extractGradient'>;
}
declare module 'react-native-svg/lib/extract/extractLengthList.js' {
  declare module.exports: $Exports<'react-native-svg/lib/extract/extractLengthList'>;
}
declare module 'react-native-svg/lib/extract/extractOpacity.js' {
  declare module.exports: $Exports<'react-native-svg/lib/extract/extractOpacity'>;
}
declare module 'react-native-svg/lib/extract/extractPolyPoints.js' {
  declare module.exports: $Exports<'react-native-svg/lib/extract/extractPolyPoints'>;
}
declare module 'react-native-svg/lib/extract/extractProps.js' {
  declare module.exports: $Exports<'react-native-svg/lib/extract/extractProps'>;
}
declare module 'react-native-svg/lib/extract/extractResponder.js' {
  declare module.exports: $Exports<'react-native-svg/lib/extract/extractResponder'>;
}
declare module 'react-native-svg/lib/extract/extractStroke.js' {
  declare module.exports: $Exports<'react-native-svg/lib/extract/extractStroke'>;
}
declare module 'react-native-svg/lib/extract/extractText.js' {
  declare module.exports: $Exports<'react-native-svg/lib/extract/extractText'>;
}
declare module 'react-native-svg/lib/extract/extractTransform.js' {
  declare module.exports: $Exports<'react-native-svg/lib/extract/extractTransform'>;
}
declare module 'react-native-svg/lib/extract/extractViewBox.js' {
  declare module.exports: $Exports<'react-native-svg/lib/extract/extractViewBox'>;
}
declare module 'react-native-svg/lib/extract/transform.js' {
  declare module.exports: $Exports<'react-native-svg/lib/extract/transform'>;
}
declare module 'react-native-svg/lib/Matrix2D.js' {
  declare module.exports: $Exports<'react-native-svg/lib/Matrix2D'>;
}
declare module 'react-native-svg/lib/resolve.js' {
  declare module.exports: $Exports<'react-native-svg/lib/resolve'>;
}
declare module 'react-native-svg/lib/SvgTouchableMixin.js' {
  declare module.exports: $Exports<'react-native-svg/lib/SvgTouchableMixin'>;
}
declare module 'react-native-svg/lib/units.js' {
  declare module.exports: $Exports<'react-native-svg/lib/units'>;
}
declare module 'react-native-svg/lib/util.js' {
  declare module.exports: $Exports<'react-native-svg/lib/util'>;
}
