// flow-typed signature: d3c9a9768c7b94a05c93f4f93653f41a
// flow-typed version: <<STUB>>/react-native-invertible-flat-list_v^1.1.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-invertible-flat-list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-invertible-flat-list' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-invertible-flat-list/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-invertible-flat-list/src/index.js' {
  declare module.exports: $Exports<'react-native-invertible-flat-list/src/index'>;
}
