// flow-typed signature: e64adbf98940874febe0c733178da5ae
// flow-typed version: <<STUB>>/react-native-fcm_vgit+https://git@github.com/ashoat/react-native-fcm.git/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-fcm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-fcm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-fcm/Examples/simple-fcm-client/__tests__/index.android' {
  declare module.exports: any;
}

declare module 'react-native-fcm/Examples/simple-fcm-client/__tests__/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-fcm/Examples/simple-fcm-client/app/App' {
  declare module.exports: any;
}

declare module 'react-native-fcm/Examples/simple-fcm-client/app/FirebaseClient' {
  declare module.exports: any;
}

declare module 'react-native-fcm/Examples/simple-fcm-client/app/FirebaseConstants' {
  declare module.exports: any;
}

declare module 'react-native-fcm/Examples/simple-fcm-client/app/Listeners' {
  declare module.exports: any;
}

declare module 'react-native-fcm/Examples/simple-fcm-client/index.android' {
  declare module.exports: any;
}

declare module 'react-native-fcm/Examples/simple-fcm-client/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-fcm/Examples/simple-fcm-client/__tests__/index.android.js' {
  declare module.exports: $Exports<'react-native-fcm/Examples/simple-fcm-client/__tests__/index.android'>;
}
declare module 'react-native-fcm/Examples/simple-fcm-client/__tests__/index.ios.js' {
  declare module.exports: $Exports<'react-native-fcm/Examples/simple-fcm-client/__tests__/index.ios'>;
}
declare module 'react-native-fcm/Examples/simple-fcm-client/app/App.js' {
  declare module.exports: $Exports<'react-native-fcm/Examples/simple-fcm-client/app/App'>;
}
declare module 'react-native-fcm/Examples/simple-fcm-client/app/FirebaseClient.js' {
  declare module.exports: $Exports<'react-native-fcm/Examples/simple-fcm-client/app/FirebaseClient'>;
}
declare module 'react-native-fcm/Examples/simple-fcm-client/app/FirebaseConstants.js' {
  declare module.exports: $Exports<'react-native-fcm/Examples/simple-fcm-client/app/FirebaseConstants'>;
}
declare module 'react-native-fcm/Examples/simple-fcm-client/app/Listeners.js' {
  declare module.exports: $Exports<'react-native-fcm/Examples/simple-fcm-client/app/Listeners'>;
}
declare module 'react-native-fcm/Examples/simple-fcm-client/index.android.js' {
  declare module.exports: $Exports<'react-native-fcm/Examples/simple-fcm-client/index.android'>;
}
declare module 'react-native-fcm/Examples/simple-fcm-client/index.ios.js' {
  declare module.exports: $Exports<'react-native-fcm/Examples/simple-fcm-client/index.ios'>;
}
declare module 'react-native-fcm/index' {
  declare module.exports: $Exports<'react-native-fcm'>;
}
declare module 'react-native-fcm/index.js' {
  declare module.exports: $Exports<'react-native-fcm'>;
}
