// flow-typed signature: ce1ee9b65eaf74748c34a270dd577b83
// flow-typed version: <<STUB>>/RelativeImageStub_vx.x.x/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'RelativeImageStub'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'RelativeImageStub' {
  declare module.exports: any;
}
