[package]
name = "rust-node-addon"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { workspace = true, features = ["napi4", "tokio_rt"] }
napi-derive = { workspace = true }
tonic = { version = "0.9.1", features = ["tls"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-stream = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
comm-opaque2 = { path = "../../../shared/comm-opaque2" }
grpc_clients = { path = "../../../shared/grpc_clients" }
lazy_static = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[build-dependencies]
napi-build = { workspace = true }
regex = { workspace = true }

[profile.release]
lto = true
