[package]
name = "backup-client-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
backup_client = { path = "../../shared/backup_client", default-features = false }
