name: Backup Build (Docker)

on:
  push:
    branches: [master]
    paths-ignore:
      - 'landing/**'
      - 'web/**'
      - 'docs/**'
      - 'keyserver/**'
      - 'desktop/**'
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: docker compose build --no-cache backup-server
        working-directory: ./services
        run: docker compose build --no-cache backup-server
