name: Farcaster signer

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: sudo ./install_protobuf.sh
        working-directory: ./scripts
        run: sudo ./install_protobuf.sh

      - name: yarn ci-cleaninstall
        run: yarn ci-cleaninstall

      - name: Build Farcaster signer
        run: |
          if ! bash -lc 'cd native && yarn build-farcaster-signer'; then
            bash -lc 'cd native && yarn clean-farcaster-signer'
            bash -lc 'cd native && yarn build-farcaster-signer'
          fi
          git diff --exit-code
