name: Remove extraneous Harbormaster git tags

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: sudo ./install_protobuf.sh
        working-directory: ./scripts
        run: sudo ./install_protobuf.sh

      - name: npm install -g yarn
        run: npm install -g yarn

      - name: yarn ci-cleaninstall
        run: yarn ci-cleaninstall

      - name: Generate tag removal script
        working-directory: ./scripts
        env:
          PHABRICATOR_API_TOKEN: ${{secrets.PHABRICATOR_API_TOKEN}}
        run: node generate-phab-tag-removal-script.js

      - name: Run tag removal script
        working-directory: ./scripts
        run: chmod +x tag_removal_script.sh && ./tag_removal_script.sh
