name: ShellCheck

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:
    inputs:
      harbormaster_build_target_phid:
        required: true
        type: string
      phabricator_diff_id:
        required: true
        type: string
      phabricator_revision_id:
        required: true
        type: string
      staging_base_ref:
        required: true
        type: string
      staging_diff_ref:
        required: true
        type: string

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout staged diff
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.staging_diff_ref }}
          fetch-depth: 0

      - name: Checkout normal ref
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: actions/checkout@v3

      - name: Install ShellCheck
        run: sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y shellcheck

      - name: Set globstar
        run: shopt -s globstar

      - name: Run ShellCheck
        run: shellcheck -x -P SCRIPTDIR **/*.sh
